version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: match_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.1.1
    container_name: match_valkey_local
    ports:
      - "6379:6379"
    volumes:
      - valkey_data_local:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: match_zookeeper_local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: match_kafka_local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin
    container_name: match_zipkin_local
    ports:
      - "9411:9411"

  match-service:
    build: .
    container_name: match-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prode_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATA_REDIS_HOST: valkey
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      EUREKA_CLIENT_ENABLED: "false"
      SPORTMONKS_TOKEN: "${SPORTMONKS_TOKEN:-ChangeMe}"
    depends_on:
      - postgres
      - valkey
      - kafka
      - zipkin

volumes:
  postgres_data_local:
  valkey_data_local:
