# Nombre del servicio para Eureka
spring.application.name=match-service
server.port=8083

#Configuracion general
spring.config.import=optional:configserver:

#Conectividad con zipkin para manejo de trazabilidad
spring.zipkin.base-url=http://localhost:9411
#spring.zipkin.base-url=http://zipkin:9411
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
#management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

#Configuracion de logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Actuator (para exponer metricas y trazas)
management.endpoints.web.exposure.include=prometheus,health,metrics
management.metrics.export.prometheus.enabled=true

#Configuracion de Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
eureka.instance.prefer-ip-address=true

#Valkey DB
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.match-events=match.events